Videojuegos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cuentas/', include('cuentas.urls')),
    path('blogs/', include('blogs.urls')),
    path('mensajes/', include('mensajes.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
   
    
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blogs'

urlpatterns = [
    path('list/', views.blog_list, name='blog_list'),
    path('detail/<int:pk>/', views.blog_detail, name='blog_detail'),
    path('rate/<int:pk>/', views.rate_blog, name='rate_blog'),
    path('create/', views.create_blog, name='create_blog'),
    path('blog/<int:pk>/delete/', views.delete_blog, name='delete_blog'),
    path('search/', views.blog_list, name='blog_search'),
    path('blog_search/', views.blog_search, name='blog_search'),
    path('', views.home_view, name='home'),
    path('about-me/', views.about_me, name='about_me'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cuentas/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'cuentas'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_view, name='login'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mensajes/urls.py
from django.urls import path
from . import views

app_name = 'mensajes'

urlpatterns = [
    path('lista/', views.message_list, name='lista_mensajes'),
    path('enviar/', views.send_message, name='enviar_mensaje'),
    path('ver/<int:pk>/', views.view_message, name='ver_mensaje'),
    path('eliminar/<int:pk>/', views.delete_message, name='eliminar_mensaje'),

]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <title>Proyecto Final</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
  <style>
    .navbar-dark .navbar-brand {
      color: #fff;
    }
    .navbar-dark .navbar-nav .nav-link {
      color: #fff;
    }
  </style>
</head>
<body style="background-color: #121212;">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="{% url 'blogs:home' %}">Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blogs:blog_list' %}">Blogs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cuentas:profile' %}">Perfil</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'mensajes:lista_mensajes' %}">Mensajes</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blogs:about_me' %}">About Me</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'cuentas:logout' %}">Cerrar Sesión</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'cuentas:login' %}">Iniciar Sesión</a>
            </li>
            <li class="nav-item">
              <a class="btn btn-primary" href="{% url 'cuentas:signup' %}">Registrarse</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <main>
    {% block content %}
    {% endblock %}
  </main>

  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/blog_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="container">
    <div class="blog-detail">
      {% if blog.image %}
        <div class="image-wrapper">
          <img src="{{ blog.image.url }}" alt="Imagen del blog" class="blog-image-detail">
        </div>
      {% else %}
        <div class="image-not-found">
          <p>Imagen no encontrada</p>
        </div>
      {% endif %}

      <div class="blog-body">
        <h2 class="blog-title">{{ blog.title }}</h2>
        <p class="blog-meta">
          <span class="blog-meta-item">Autor: {{ blog.author }}</span>
          <span class="blog-meta-item">Fecha: {{ blog.date }}</span>
          <span class="blog-meta-item">Rating: <span class="gold-star">&#9733;</span> {{ blog.rating }}</span>
        </p>
        <p>{{ blog.body }}</p>
      </div>

      <div class="content-section">
        <div class="comment-section">
          <h2>Comentarios</h2>
          <ul class="comment-list">
            {% for comment in comments %}
              <li class="comment-item">
                <p class="comment-content">
                  <span class="comment-author">{{ comment.author }}</span>
                  <span class="comment-text">{{ comment.text }}</span>
                </p>
                <p class="comment-date">{{ comment.created_at }}</p>
              </li>
              {% for reply in comment.replies.all %}
                <ul class="reply-list">
                  <li class="reply-item">
                    <p class="reply-content">
                      <span class="reply-author">{{ reply.author }}</span>
                      <span class="reply-text">{{ reply.text }}</span>
                    </p>
                    <p class="reply-date">{{ reply.created_at }}</p>
                  </li>
                </ul>
              {% endfor %}
            {% endfor %}
          </ul>

          <h2>Agregar Comentario</h2>
          <form method="post" action="{% url 'blogs:blog_detail' pk=blog.pk %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Enviar Comentario</button>
          </form>
        </div>

        <div class="rating-section">
          {% if has_rated_blog %}
              <p>Ya has valorado este blog.</p>
          {% else %}
              <h2>Valorar</h2>
              <form method="post" action="{% url 'blogs:rate_blog' pk=blog.pk %}">
                  {% csrf_token %}
                  <div class="rating-options">
                      {{ rating_form.rating }}
                  </div>
                  <button type="submit" class="btn btn-primary">Valorar</button>
              </form>
          {% endif %}
        </div>
      </div>

      <div class="action-section">
        <a href="{% url 'blogs:blog_list' %}" class="return-link">Volver a la lista de blogs</a>

        {% if blog.author == request.user %}
          <form method="post" action="{% url 'blogs:delete_blog' pk=blog.pk %}" class="delete-form">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Eliminar blog</button>
          </form>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

templates/blog_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="container">
    <h1 class="mb-4">Blogs</h1>

    <a href="{% url 'blogs:create_blog' %}" class="btn btn-primary mb-3">Crear nuevo blog</a>

    <form method="GET" action="{% url 'blogs:blog_search' %}" class="search-form">
      <div class="input-group input-group-xs mb-3">
        <input type="text" name="q" class="form-control" placeholder="Buscar blogs">
        <div class="input-group-append">
          <button type="submit" class="btn btn-primary">Buscar</button>
        </div>
      </div>
    </form>

    <ul class="blog-list">
      {% for blog in page_obj %}
        <li class="blog-item mb-4">
          <a href="{% url 'blogs:blog_detail' blog.pk %}">
            <div class="blog-thumbnail">
              <h2 class="blog-title">{{ blog.title }}</h2>
              {% if blog.image %}
                <img class="blog-image" src="{{ blog.image.url }}" alt="{{ blog.title }}">
              {% else %}
                <div class="image-not-found">
                  <p>Imagen no encontrada</p>
                </div>
              {% endif %}
              <div class="blog-meta">
                <p class="blog-date">{{ blog.date }}</p>
                <div class="blog-rating">
                  <span class="rating-number">{{ blog.rating|default_if_none:0|floatformat:1 }}</span>
                  <span class="star">&#9733;</span>
                </div>
              </div>
            </div>
          </a>
        </li>
      {% empty %}
        <li>No se encontraron blogs.</li>
      {% endfor %}
    </ul>

    <div class="pagination">
      {% if page_obj.has_previous %}
        <a href="?page=1" class="btn btn-secondary">&laquo; Primera</a>
        <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-secondary">Anterior</a>
      {% endif %}

      <span class="current-page btn btn-primary disabled">{{ page_obj.number }}</span>

      {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="btn btn-secondary">Siguiente</a>
        <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-secondary">Última &raquo;</a>
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/blog_search.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="container">
    <h1 class="mb-4">Búsqueda de Blogs</h1>

    <form method="GET" action="{% url 'blogs:blog_search' %}" class="search-form">
      <div class="input-group input-group-xs mb-3">
        <input type="text" name="q" class="form-control" placeholder="Buscar blogs" value="{{ query }}">
        <div class="input-group-append">
          <button type="submit" class="btn btn-primary">Buscar</button>
        </div>
      </div>
    </form>

    {% if page_obj.has_other_pages %}
      <p class="text-muted">Mostrando resultados para la búsqueda: "{{ query }}"</p>
    {% endif %}

    <ul class="blog-list">
      {% for blog in page_obj %}
        <li class="blog-item mb-4">
          <a href="{% url 'blogs:blog_detail' blog.pk %}">
            <div class="blog-thumbnail">
              <h2 class="blog-title">{{ blog.title }}</h2>
              {% if blog.image %}
                <img class="blog-image" src="{{ blog.image.url }}" alt="{{ blog.title }}">
              {% else %}
                <div class="image-not-found">
                  <p>Imagen no encontrada</p>
                </div>
              {% endif %}
              <div class="blog-meta">
                <p class="blog-date">{{ blog.date }}</p>
                <div class="blog-rating">
                  <span class="rating-number">{{ blog.rating|default_if_none:0|floatformat:1 }}</span>
                  <span class="star">&#9733;</span>
                </div>
              </div>
            </div>
          </a>
        </li>
      {% empty %}
        <li>No se encontraron blogs.</li>
      {% endfor %}
    </ul>

    <div class="pagination">
      {% if page_obj.has_previous %}
        <a href="?q={{ query }}&page=1" class="btn btn-secondary">&laquo; Primera</a>
        <a href="?q={{ query }}&page={{ page_obj.previous_page_number }}" class="btn btn-secondary">Anterior</a>
      {% endif %}

      <span class="current-page btn btn-primary disabled">{{ page_obj.number }}</span>

      {% if page_obj.has_next %}
        <a href="?q={{ query }}&page={{ page_obj.next_page_number }}" class="btn btn-secondary">Siguiente</a>
        <a href="?q={{ query }}&page={{ page_obj.paginator.num_pages }}" class="btn btn-secondary">Última &raquo;</a>
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/create_blog.html
{% extends 'base.html' %}

{% block content %}
  <h1>Crear un nuevo blog</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Publicar</button>
  </form>
{% endblock %}

templates/delete_blog.html
{% extends 'base.html' %}

{% block content %}
  <h1>Eliminar Blog</h1>
  <p>¿Estás seguro de que deseas eliminar el siguiente blog?</p>
  <h3>{{ blog.title }}</h3>
  
  <form method="post">
    {% csrf_token %}
    <button type="submit">Eliminar</button>
    <a href="{% url 'blogs:blog_detail' pk=blog.pk %}">Cancelar</a>
  </form>
{% endblock %}

templates/editar_perfil.html
<!-- En editar_perfil.html -->
{% extends 'base.html' %}

{% block content %}
  <h1>Editar Perfil</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
  </form>
{% endblock %}

templates/enviar_mensaje.html
{% extends 'base.html' %}

{% block content %}
  <h1>Enviar Mensaje</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Enviar</button>
  </form>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class="home-section">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 offset-lg-2">
        <h1 class="text-center">Bienvenido a Proyecto Final</h1>
        <p class="lead text-center">Los mejores videojuegos del mundo.</p>
      </div>
    </div>
    <div class="row mt-5">
      <div class="col-lg-6">
        <h2>Características principales</h2>
        <ul>
          <li>Los últimos videojuegos</li>
          <li>Noticias y actualizaciones </li>
          <li>Comunidad activa de jugadores y entusiastas</li>
        </ul>
        <a href="{% url 'blogs:blog_list' %}" class="btn btn-primary">Explorar blogs</a>
      </div>
      <div class="col-lg-6">
        <h2>Últimos blogs publicados</h2>
        <ul class="list-group">
          {% for blog in latest_blogs %}
          <li class="list-group-item">
            <h4>{{ blog.title }}</h4>
            <p>{{ blog.date }}</p>
          </li>
          {% empty %}
          <li class="list-group-item">No se encontraron blogs.</li>
          {% endfor %}
        </ul>
        <a href="{% url 'blogs:blog_list' %}" class="btn btn-primary">Ver todos los blogs</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/lista_mensajes.html
{% extends 'base.html' %}

{% block content %}
  <div class="message-section">
    <h1>Mensajes</h1>
    <a href="{% url 'mensajes:enviar_mensaje' %}" class="btn btn-primary">Enviar Mensaje</a>
    <hr>
  
    {% if messages %}
      <ul class="message-list">
        {% for message in messages %}
          <li class="message-item">
            <a href="{% url 'mensajes:ver_mensaje' message.pk %}" class="message-link">
              <h3 class="message-subject">{{ message.subject }}</h3>
              <p class="message-sender">De: {{ message.sender }}</p>
              <p class="message-timestamp">Fecha: {{ message.timestamp }}</p>
            </a>
          </li>
        {% empty %}
          <li>No hay mensajes disponibles.</li>
        {% endfor %}
      </ul>
    {% else %}
      <p>No hay mensajes disponibles.</p>
    {% endif %}
  </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}
  <h1>Iniciar Sesión</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Iniciar Sesión</button>
  </form>
  <p>No tienes una cuenta? <a href="{% url 'cuentas:signup' %}" class="btn">Registrarse</a></p>
{% endblock %}

templates/message_form.html
{% extends 'base.html' %}

{% block content %}
  <h1>Redactar Mensaje</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Enviar Mensaje</button>
  </form>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block content %}
  <h1>Registrarse</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Registrarse</button>
  </form>
  <p>¿Ya tienes una cuenta? <a href="{% url 'cuentas:login' %}">Iniciar sesión aquí</a></p>
{% endblock %}

templates/update_page.html
{% extends 'base.html' %}

{% block content %}
  <h1>Editar Página</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Actualizar Página</button>
  </form>
{% endblock %}